#!/usr/bin/env bash
#
# Regenerate MacDown's "GitHub-2020" preview style from GitHub's published
# markdown CSS (the maintained github-markdown-css package, served prebuilt
# from the jsDelivr CDN).
#
# The output, MacDown/Resources/Styles/GitHub-2020.css, is COMMITTED to the
# repository, so the app build does not depend on this script. Run it by hand
# only when you want to refresh the style.
#
# This replaces the original node-sass + primer-markdown@4 pipeline, which no
# longer builds on current toolchains (node-sass is unsupported on modern
# Node, and primer-markdown has been unmaintained since ~2020).
#
# Requirements: curl (preinstalled on macOS; also `brew install curl`).
#
set -euo pipefail
cd "$(dirname "$0")"

# github-markdown-css major version. Bump intentionally to adopt a newer
# GitHub look, then commit the regenerated CSS.
readonly version='5'
readonly url="https://cdn.jsdelivr.net/npm/github-markdown-css@${version}/github-markdown.css"
readonly out='../../MacDown/Resources/Styles/GitHub-2020.css'

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# Combined light + dark stylesheet (auto-switches via prefers-color-scheme).
curl -fsSL "$url" -o "$tmp"

# github-markdown-css scopes every rule under .markdown-body; MacDown applies
# the preview style to the whole document, so retarget that scope to body
# (matching the other committed GitHub styles).
{
    echo '/* Generated by Tools/GitHub-style-generator/generate.sh from the'
    echo '   github-markdown-css package. Do not edit by hand; re-run that'
    echo "   script to refresh (github-markdown-css major version ${version}). */"
    sed 's/\.markdown-body/body/g' "$tmp"
} > "$out"

echo "Wrote ${out} ($(wc -l < "$out" | tr -d ' ') lines)"
